# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fca03fc4d5ff169112daed38b29f8db4ec3e0acef3189ca56ab2d671da609b853c41e62b509d0b3bc172e5a5e35c343bdba5462de1811b11bec4a1753beb5b0e

test:
  secret_key_base: 82edffc743332b16fde238a9af1de96053aef5a303589865e4c56270d024c3bf85fe420a0794c00e4fe6febcac8a8ccefd2b1ab4e930abb0df94213a3136198b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
